<?php

namespace Database\Seeders;

use App\Models\Property;
use App\Models\User;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get or create a test user
        $user = User::firstOrCreate(
            ['email' => 'seller@saveonyourhome.com'],
            [
                'name' => 'John Seller',
                'password' => bcrypt('password'),
                'role' => 'seller',
                'is_active' => true,
                'email_verified_at' => now(),
            ]
        );

        $properties = [
            [
                'user_id' => $user->id,
                'property_title' => 'Beautiful Family Home in Tulsa',
                'developer' => 'Simmons Homes',
                'property_type' => 'single-family-home',
                'status' => 'for-sale',
                'listing_status' => 'for_sale',
                'price' => 299000,
                'address' => '1234 S Yorktown Ave',
                'city' => 'Tulsa',
                'state' => 'Oklahoma',
                'zip_code' => '74104',
                'subdivision' => 'Oak Hills',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'full_bathrooms' => 3,
                'half_bathrooms' => 0,
                'sqft' => 2500,
                'lot_size' => 10890,
                'year_built' => 2015,
                'description' => 'This stunning 4-bedroom home features an open floor plan, modern kitchen with granite countertops, hardwood floors throughout, and a spacious backyard perfect for entertaining. Located in a quiet neighborhood with easy access to schools and shopping.',
                'features' => ['Central AC', 'Central Heat', 'Hardwood Floors', 'Granite Countertops', 'Stainless Steel Appliances', 'Fenced Yard', 'Garage'],
                'photos' => ['https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=800'],
                'video_tour_url' => 'https://www.youtube.com/watch?v=example1',
                'virtual_tour_url' => 'https://my.matterport.com/show/?m=example1',
                'floor_plan_url' => 'https://example.com/floorplans/property1.pdf',
                'contact_name' => 'John Seller',
                'contact_email' => 'seller@saveonyourhome.com',
                'contact_phone' => '(918) 555-0123',
                'is_active' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'latitude' => 36.1340,
                'longitude' => -95.9520,
            ],
            [
                'user_id' => $user->id,
                'property_title' => 'Modern Condo in Downtown OKC',
                'developer' => 'Clayco Development',
                'property_type' => 'condos-townhomes-co-ops',
                'status' => 'for-sale',
                'listing_status' => 'for_sale',
                'price' => 185000,
                'address' => '100 W Main St',
                'city' => 'Oklahoma City',
                'state' => 'Oklahoma',
                'zip_code' => '73102',
                'subdivision' => 'Downtown District',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'full_bathrooms' => 2,
                'half_bathrooms' => 0,
                'sqft' => 1200,
                'lot_size' => null,
                'year_built' => 2018,
                'description' => 'Sleek modern condo in the heart of downtown Oklahoma City. Features floor-to-ceiling windows, contemporary finishes, and stunning city views. Building amenities include fitness center, rooftop deck, and secure parking.',
                'features' => ['Central AC', 'Central Heat', 'Walk-In Closet', 'Updated Kitchen', 'Security System', 'Balcony'],
                'photos' => ['https://images.pexels.com/photos/1643389/pexels-photo-1643389.jpeg?auto=compress&cs=tinysrgb&w=800'],
                'contact_name' => 'John Seller',
                'contact_email' => 'seller@saveonyourhome.com',
                'contact_phone' => '(918) 555-0123',
                'is_active' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'latitude' => 35.4676,
                'longitude' => -97.5164,
            ],
            [
                'user_id' => $user->id,
                'property_title' => 'Spacious Ranch in Norman',
                'developer' => 'Ideal Homes',
                'property_type' => 'single-family-home',
                'status' => 'for-sale',
                'listing_status' => 'for_sale',
                'price' => 425000,
                'address' => '1200 Asp Ave',
                'city' => 'Norman',
                'state' => 'Oklahoma',
                'zip_code' => '73072',
                'subdivision' => 'University Park',
                'bedrooms' => 5,
                'bathrooms' => 4,
                'full_bathrooms' => 3,
                'half_bathrooms' => 2,
                'sqft' => 3200,
                'lot_size' => 21780,
                'year_built' => 2010,
                'description' => 'Expansive ranch-style home near the University of Oklahoma. Features include a chef\'s kitchen, formal dining room, home office, and finished basement. The large backyard includes a pool and covered patio.',
                'features' => ['Central AC', 'Central Heat', 'Swimming Pool', 'Covered Patio', 'Fireplace', 'Granite Countertops', 'Hardwood Floors', 'Garage', 'Sprinkler System'],
                'photos' => ['https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=800'],
                'contact_name' => 'John Seller',
                'contact_email' => 'seller@saveonyourhome.com',
                'contact_phone' => '(918) 555-0123',
                'is_active' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'latitude' => 35.2226,
                'longitude' => -97.4395,
            ],
            [
                'user_id' => $user->id,
                'property_title' => 'Charming Starter Home in Edmond',
                'developer' => 'Landmark Fine Homes',
                'property_type' => 'single-family-home',
                'status' => 'for-sale',
                'listing_status' => 'for_sale',
                'price' => 275000,
                'address' => '1500 E Covell Rd',
                'city' => 'Edmond',
                'state' => 'Oklahoma',
                'zip_code' => '73034',
                'subdivision' => 'Covell Estates',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'full_bathrooms' => 2,
                'half_bathrooms' => 0,
                'sqft' => 1650,
                'lot_size' => 6534,
                'year_built' => 2012,
                'description' => 'Perfect starter home in the highly sought-after Edmond school district. Features an updated kitchen, new flooring, and a nice backyard. Move-in ready!',
                'features' => ['Central AC', 'Central Heat', 'Updated Kitchen', 'Fenced Yard', 'Garage', 'Carpet'],
                'photos' => ['https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=800'],
                'contact_name' => 'John Seller',
                'contact_email' => 'seller@saveonyourhome.com',
                'contact_phone' => '(918) 555-0123',
                'is_active' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'latitude' => 35.6528,
                'longitude' => -97.4395,
            ],
            [
                'user_id' => $user->id,
                'property_title' => 'Luxury Estate in Broken Arrow',
                'developer' => 'Shaw Homes',
                'property_type' => 'single-family-home',
                'status' => 'for-sale',
                'listing_status' => 'for_sale',
                'price' => 650000,
                'address' => '4500 W Kenosha St',
                'city' => 'Broken Arrow',
                'state' => 'Oklahoma',
                'zip_code' => '74012',
                'subdivision' => 'Aspen Creek',
                'bedrooms' => 6,
                'bathrooms' => 5,
                'full_bathrooms' => 4,
                'half_bathrooms' => 2,
                'sqft' => 4500,
                'lot_size' => 21780,
                'year_built' => 2019,
                'description' => 'Stunning luxury estate with every amenity imaginable. Features include a gourmet kitchen, wine cellar, home theater, and resort-style backyard with pool and outdoor kitchen. Smart home technology throughout.',
                'features' => ['Central AC', 'Central Heat', 'Swimming Pool', 'Hot Tub', 'Fireplace', 'Granite Countertops', 'Hardwood Floors', 'Walk-In Closet', 'Security System', 'Sprinkler System', 'Covered Patio', 'Garage'],
                'photos' => ['https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=800'],
                'video_tour_url' => 'https://www.youtube.com/watch?v=luxuryestate',
                'virtual_tour_url' => 'https://my.matterport.com/show/?m=luxuryestate',
                'contact_name' => 'John Seller',
                'contact_email' => 'seller@saveonyourhome.com',
                'contact_phone' => '(918) 555-0123',
                'is_active' => true,
                'is_featured' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'latitude' => 36.0609,
                'longitude' => -95.7975,
            ],
            [
                'user_id' => $user->id,
                'property_title' => 'Cozy Home in Lawton',
                'developer' => 'Homes by Taber',
                'property_type' => 'single-family-home',
                'status' => 'for-sale',
                'listing_status' => 'for_sale',
                'price' => 165000,
                'address' => '1002 SW Lee Blvd',
                'city' => 'Lawton',
                'state' => 'Oklahoma',
                'zip_code' => '73501',
                'subdivision' => null,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'full_bathrooms' => 2,
                'half_bathrooms' => 0,
                'sqft' => 1400,
                'lot_size' => 6970,
                'year_built' => 1998,
                'description' => 'Well-maintained home with recent updates including new roof, HVAC, and water heater. Great location near Fort Sill. Perfect for military families or first-time buyers.',
                'features' => ['Central AC', 'Central Heat', 'Fenced Yard', 'Garage', 'Updated Bathroom'],
                'photos' => ['https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?auto=compress&cs=tinysrgb&w=800'],
                'contact_name' => 'John Seller',
                'contact_email' => 'seller@saveonyourhome.com',
                'contact_phone' => '(918) 555-0123',
                'is_active' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'latitude' => 34.6036,
                'longitude' => -98.4003,
            ],
            [
                'user_id' => $user->id,
                'property_title' => 'Land for Development',
                'developer' => null,
                'property_type' => 'land',
                'status' => 'for-sale',
                'listing_status' => 'for_sale',
                'price' => 89000,
                'address' => '1900 S Eastern Ave',
                'city' => 'Moore',
                'state' => 'Oklahoma',
                'zip_code' => '73160',
                'subdivision' => null,
                'bedrooms' => 0,
                'bathrooms' => 0,
                'full_bathrooms' => 0,
                'half_bathrooms' => 0,
                'sqft' => 0,
                'lot_size' => 43560,
                'year_built' => null,
                'description' => 'Beautiful 1-acre lot ready for your dream home. Utilities available at the street. Located in a growing area with easy highway access. No HOA restrictions.',
                'features' => ['Mature Trees'],
                'photos' => ['https://images.pexels.com/photos/440731/pexels-photo-440731.jpeg?auto=compress&cs=tinysrgb&w=800'],
                'contact_name' => 'John Seller',
                'contact_email' => 'seller@saveonyourhome.com',
                'contact_phone' => '(918) 555-0123',
                'is_active' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'latitude' => 35.3395,
                'longitude' => -97.4867,
            ],
            [
                'user_id' => $user->id,
                'property_title' => 'Multi-Family Investment Property',
                'developer' => 'Wallace Engineering',
                'property_type' => 'multi-family',
                'status' => 'for-sale',
                'listing_status' => 'for_sale',
                'price' => 385000,
                'address' => '715 S Husband St',
                'city' => 'Stillwater',
                'state' => 'Oklahoma',
                'zip_code' => '74074',
                'subdivision' => null,
                'bedrooms' => 8,
                'bathrooms' => 4,
                'full_bathrooms' => 4,
                'half_bathrooms' => 0,
                'sqft' => 3600,
                'lot_size' => 10890,
                'year_built' => 2005,
                'description' => 'Excellent investment opportunity! 4-unit property near Oklahoma State University. All units currently rented with strong rental history. Each unit has 2 bedrooms and 1 bathroom.',
                'features' => ['Central AC', 'Central Heat', 'Garage'],
                'photos' => ['https://images.pexels.com/photos/1115804/pexels-photo-1115804.jpeg?auto=compress&cs=tinysrgb&w=800'],
                'contact_name' => 'John Seller',
                'contact_email' => 'seller@saveonyourhome.com',
                'contact_phone' => '(918) 555-0123',
                'is_active' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'latitude' => 36.1156,
                'longitude' => -97.0584,
            ],
            [
                'user_id' => $user->id,
                'property_title' => 'Historic Home in Midtown Tulsa',
                'developer' => 'McIntosh Construction',
                'property_type' => 'single-family-home',
                'status' => 'for-sale',
                'listing_status' => 'for_sale',
                'price' => 375000,
                'address' => '1821 S Boston Ave',
                'city' => 'Tulsa',
                'state' => 'Oklahoma',
                'zip_code' => '74119',
                'subdivision' => 'Midtown',
                'bedrooms' => 4,
                'bathrooms' => 2.5,
                'full_bathrooms' => 2,
                'half_bathrooms' => 1,
                'sqft' => 2800,
                'lot_size' => 8712,
                'year_built' => 1925,
                'description' => 'Beautifully restored 1920s craftsman home in historic Midtown Tulsa. Original hardwood floors, built-in cabinetry, and period details throughout. Updated kitchen and bathrooms while maintaining historic charm.',
                'features' => ['Central AC', 'Central Heat', 'Hardwood Floors', 'Fireplace', 'Covered Patio', 'Mature Trees', 'Garage'],
                'photos' => ['https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg?auto=compress&cs=tinysrgb&w=800'],
                'contact_name' => 'John Seller',
                'contact_email' => 'seller@saveonyourhome.com',
                'contact_phone' => '(918) 555-0123',
                'is_active' => true,
                'is_featured' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'latitude' => 36.1397,
                'longitude' => -95.9784,
            ],
            // SOLD Properties
            [
                'user_id' => $user->id,
                'property_title' => 'SOLD - Classic Bungalow in Brookside',
                'developer' => null,
                'property_type' => 'single-family-home',
                'status' => 'sold',
                'listing_status' => 'sold',
                'price' => 285000,
                'address' => '3521 S Peoria Ave',
                'city' => 'Tulsa',
                'state' => 'Oklahoma',
                'zip_code' => '74105',
                'subdivision' => 'Brookside',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'full_bathrooms' => 2,
                'half_bathrooms' => 0,
                'sqft' => 1800,
                'lot_size' => 7405,
                'year_built' => 1940,
                'description' => 'Charming bungalow in the heart of Brookside. This home sold quickly due to its prime location and classic charm.',
                'features' => ['Central AC', 'Central Heat', 'Hardwood Floors', 'Fireplace', 'Fenced Yard'],
                'photos' => ['https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg?auto=compress&cs=tinysrgb&w=800'],
                'contact_name' => 'John Seller',
                'contact_email' => 'seller@saveonyourhome.com',
                'contact_phone' => '(918) 555-0123',
                'is_active' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'latitude' => 36.1098,
                'longitude' => -95.9747,
            ],
            [
                'user_id' => $user->id,
                'property_title' => 'SOLD - Modern Home in Jenks',
                'developer' => 'Taber Homes',
                'property_type' => 'single-family-home',
                'status' => 'sold',
                'listing_status' => 'sold',
                'price' => 340000,
                'address' => '525 W Main St',
                'city' => 'Jenks',
                'state' => 'Oklahoma',
                'zip_code' => '74037',
                'subdivision' => 'Riverwalk',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'full_bathrooms' => 3,
                'half_bathrooms' => 0,
                'sqft' => 2400,
                'lot_size' => 7841,
                'year_built' => 2020,
                'description' => 'Beautiful modern home near the Arkansas River. Sold with multiple offers within the first week!',
                'features' => ['Central AC', 'Central Heat', 'Granite Countertops', 'Stainless Steel Appliances', 'Garage', 'Sprinkler System'],
                'photos' => ['https://images.pexels.com/photos/1438832/pexels-photo-1438832.jpeg?auto=compress&cs=tinysrgb&w=800'],
                'contact_name' => 'John Seller',
                'contact_email' => 'seller@saveonyourhome.com',
                'contact_phone' => '(918) 555-0123',
                'is_active' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'latitude' => 36.0228,
                'longitude' => -95.9683,
            ],
            // FOR RENT Properties
            [
                'user_id' => $user->id,
                'property_title' => 'Downtown Tulsa Loft for Rent',
                'developer' => 'Brady Arts District',
                'property_type' => 'condos-townhomes-co-ops',
                'status' => 'for-rent',
                'listing_status' => 'for_rent',
                'price' => 1500,
                'address' => '111 E Brady St',
                'city' => 'Tulsa',
                'state' => 'Oklahoma',
                'zip_code' => '74103',
                'subdivision' => 'Brady Arts District',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'full_bathrooms' => 1,
                'half_bathrooms' => 0,
                'sqft' => 850,
                'lot_size' => null,
                'year_built' => 2016,
                'description' => 'Stylish loft in the Brady Arts District. Walking distance to restaurants, shops, and entertainment. Rent includes water and trash.',
                'features' => ['Central AC', 'Central Heat', 'Hardwood Floors', 'Walk-In Closet', 'Balcony'],
                'photos' => ['https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800'],
                'contact_name' => 'John Seller',
                'contact_email' => 'seller@saveonyourhome.com',
                'contact_phone' => '(918) 555-0123',
                'is_active' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'latitude' => 36.1596,
                'longitude' => -95.9901,
            ],
            [
                'user_id' => $user->id,
                'property_title' => 'Family Home for Rent in Bixby',
                'developer' => null,
                'property_type' => 'single-family-home',
                'status' => 'for-rent',
                'listing_status' => 'for_rent',
                'price' => 2200,
                'address' => '8702 E 121st St S',
                'city' => 'Bixby',
                'state' => 'Oklahoma',
                'zip_code' => '74008',
                'subdivision' => 'Memorial Estates',
                'bedrooms' => 4,
                'bathrooms' => 2.5,
                'full_bathrooms' => 2,
                'half_bathrooms' => 1,
                'sqft' => 2100,
                'lot_size' => 8712,
                'year_built' => 2014,
                'description' => 'Spacious family home in Bixby school district. Large backyard, 2-car garage, and all appliances included. Available immediately.',
                'features' => ['Central AC', 'Central Heat', 'Fenced Yard', 'Garage', 'Stainless Steel Appliances', 'Carpet'],
                'photos' => ['https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg?auto=compress&cs=tinysrgb&w=800'],
                'contact_name' => 'John Seller',
                'contact_email' => 'seller@saveonyourhome.com',
                'contact_phone' => '(918) 555-0123',
                'is_active' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'latitude' => 35.9634,
                'longitude' => -95.8803,
            ],
            [
                'user_id' => $user->id,
                'property_title' => 'Apartment for Rent Near OU',
                'developer' => 'Campus Living',
                'property_type' => 'condos-townhomes-co-ops',
                'status' => 'for-rent',
                'listing_status' => 'for_rent',
                'price' => 950,
                'address' => '900 Asp Ave',
                'city' => 'Norman',
                'state' => 'Oklahoma',
                'zip_code' => '73069',
                'subdivision' => null,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'full_bathrooms' => 1,
                'half_bathrooms' => 0,
                'sqft' => 750,
                'lot_size' => null,
                'year_built' => 2008,
                'description' => 'Perfect student housing! Walking distance to OU campus. Utilities included in rent. On-site laundry and parking available.',
                'features' => ['Central AC', 'Central Heat', 'Updated Kitchen'],
                'photos' => ['https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=800'],
                'contact_name' => 'John Seller',
                'contact_email' => 'seller@saveonyourhome.com',
                'contact_phone' => '(918) 555-0123',
                'is_active' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'latitude' => 35.2089,
                'longitude' => -97.4456,
            ],
        ];

        foreach ($properties as $propertyData) {
            Property::create($propertyData);
        }

        $this->command->info('Created ' . count($properties) . ' sample properties!');
    }
}
